#!/bin/bash

# Update pip
python -m pip install --upgrade pip setuptools wheel

# Install pre-commit
python -m pip install --upgrade pre-commit
pre-commit install --install-hooks
pre-commit autoupdate

# Install pylint
python -m pip install --upgrade pylint
pylint --generate-rcfile > ~/.pylintrc

# Install sphinx for documentation
python -m pip install sphinx sphinx-rtd-theme sphinx-autobuild sphinx-autodoc-typehints
mkdir -p docs/source/_static

# Install coverage for testing
python -m pip install coverage

# Install bushfire_drone_simulation
python -m pip install -e bushfire_drone_simulation

echo "Congratulations! The ANU Bushfire Initiative Drone Simulation is now installed."
