# This workflow will install the program and run the pre-commit linting/testing with python 3.8

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        source tools/install-dev-env
    - name: Setup Display
      run: |
        disp=:99
        screen=0
        geom=640x480x24
        exec Xvfb $disp -screen $screen $geom 2>/tmp/Xvfb.log &
        export DISPLAY=:99
    - name: Run pytest
      run: |
          python -m coverage run --source=. -m pytest
          python -m coverage xml
    - name: Upload coverage
      run: |
          export CODECOV_TOKEN=ac54371c-aacc-460f-bcb6-c545418d7ae6
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
