# This workflow will install the program and run the pre-commit linting/testing with python 3.8

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        source tools/install-dev-env
        sudo apt update && sudo apt install ghostscript tk xvfb -y
    - name: Setup display and run pytest
      run: |
        disp=:99
        screen=0
        geom=640x480x24
        Xvfb $disp -screen $screen $geom &
        export DISPLAY=:99
        python -m coverage run --source=. -m pytest
        python -m coverage xml -i
    - name: Upload coverage
      run: |
          export CODECOV_TOKEN=fca5ec9c-2568-4c8b-9e47-1b570b85fad4
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
